- block:
  - name: Add jenkins GPG key for ubuntu
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present

  - name: Add jenkins repository
    apt_repository:
      repo: deb [arch=amd64] https://pkg.jenkins.io/debian-stable binary/
      filename: jenkins
      state: present